### ISSUE TITLE
Levantamento de tabelas de conversão 

### ISSUE THREAD

**Issue by RafaelEstatistico** [lamfo-unb/AutomationJobs#1]
Como não há tradutor de **CBO2002** para **Job Zone** é preciso realizar as conversões na seguinte ordem:
+ CBO2002 -----> ISCO88
+ ISCO88 -------> ISCO08
+ ISCO08 -------> SOC
+ SOC -----------> Job Zone

**Comment by PedroBSB** [comment]
Nossa.. Tudo isso ? Mas existe pareamento entre essas: 
ISCO88 -------> ISCO08
ISCO08 -------> SOC
SOC -----------> Job Zone ?
Porque se tivermos que fazer de maneira nebulosa todas essas conversões é melhor a gente inventar um grau de automação. Ou então fazer direto CBO2002------> Job Zone

**Comment by RafaelEstatistico** [comment]
Temos pareamento para todas, mas admito que por passarmos por tantas conversões talvez qualidade do  CBO2002------> Job Zone não seja tão boa.

As fontes das conversões são:
+ [CBO2002 -----> ISCO88](http://www.mtecbo.gov.br/cbosite/pages/tabua/ConsultasConversao.jsf) Com uso de scraping
+ [ISCO88 -------> ISCO08](http://www.ilo.org/public/english/bureau/stat/isco/isco08/)
+ [ISCO08 -------> SOC](https://www.bls.gov/soc/ISCO_SOC_Crosswalk.xls)
+ [SOC -----------> Job Zone](https://www.onetonline.org/find/zone/All_Job_Zones.csv?fmt=csv&z=0)
